### ISSUE TITLE
cant put default values selected

### ISSUE THREAD

**Issue by itsnasser** [satriaajiputra/select-beauty#1]
<select name="work-condition" id="work-condition" class="form-control">
  <option value="1" icon="iw-way" selected="selected">Remote Location</option>
  <option value="2" icon="iw-crane">Work From Height</option>
  <option value="3" icon="iw-scope">Field Visit</option>
  <option value="4" icon="iw-excavator">Active Machinery</option>
</select>

**Comment by satriaajiputra** [comment]
**First**, update your ``select-beauty`` with the new version

After that, you can set default selected values by using this script
```javascript
var beauty = new SelectBeauty({
  el: '#your-element', // element with only id selector
  placeholder: 'Select Something...', // placeholder for button
  length: 5, // max length to show the selected items
  max: 10, // max length to select the item
  selected: [1,3,7,17] // set default selected value
});
```

At that script, you can add ``selected`` property for setting default selected values
